/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mini_project;
import java.awt.Color;
import javax.swing.JFrame;
import java.util.Date;

/**
 *
 * @author pande
 */
public class AddFees extends JFrame {

    /**
     * Creates new form AddPage
     */
    public AddFees() {
        initComponents();
        /*Date d1=new Date();
        java.Date d2=new Date();
        */
    }
    public void displayCashFirst()
    {
        check
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        Home_panel = new javax.swing.JPanel();
        SBHome = new javax.swing.JLabel();
        Search_panel = new javax.swing.JPanel();
        SBSearch = new javax.swing.JLabel();
        Home_panel1 = new javax.swing.JPanel();
        Edit_panel = new javax.swing.JLabel();
        Home_panel2 = new javax.swing.JPanel();
        Course_panel = new javax.swing.JLabel();
        View_panel = new javax.swing.JPanel();
        SBView = new javax.swing.JLabel();
        Logout_panel = new javax.swing.JPanel();
        SBLogout = new javax.swing.JLabel();
        Back_panel = new javax.swing.JPanel();
        SBBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Id = new javax.swing.JLabel();
        IdText = new javax.swing.JTextField();
        PayMode = new javax.swing.JLabel();
        PayText = new javax.swing.JTextField();
        ChequeNum = new javax.swing.JLabel();
        ChequeText = new javax.swing.JTextField();
        BankNm = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        BankText = new javax.swing.JTextField();
        Receiver = new javax.swing.JLabel();
        ReceiverText = new javax.swing.JTextField();
        Course = new javax.swing.JLabel();
        CourseText = new javax.swing.JComboBox<>();
        AmountRup = new javax.swing.JLabel();
        AmountRupText = new javax.swing.JTextField();
        AmountWords = new javax.swing.JLabel();
        AmountWordsText = new javax.swing.JTextField();
        Remarks = new javax.swing.JLabel();
        RemarksText = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 0, 102));

        Home_panel.setBackground(new java.awt.Color(0, 0, 102));
        Home_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        SBHome.setBackground(new java.awt.Color(255, 255, 255));
        SBHome.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        SBHome.setForeground(new java.awt.Color(255, 255, 255));
        SBHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\home.png")); // NOI18N
        SBHome.setText("HOME");
        SBHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SBHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SBHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Home_panelLayout = new javax.swing.GroupLayout(Home_panel);
        Home_panel.setLayout(Home_panelLayout);
        Home_panelLayout.setHorizontalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(SBHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Home_panelLayout.setVerticalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SBHome, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        Search_panel.setBackground(new java.awt.Color(0, 0, 102));
        Search_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        SBSearch.setBackground(new java.awt.Color(255, 255, 255));
        SBSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SBSearch.setForeground(new java.awt.Color(255, 255, 255));
        SBSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\search2.png")); // NOI18N
        SBSearch.setText("SEARCH RECORD");
        SBSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SBSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SBSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Search_panelLayout = new javax.swing.GroupLayout(Search_panel);
        Search_panel.setLayout(Search_panelLayout);
        Search_panelLayout.setHorizontalGroup(
            Search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SBSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Search_panelLayout.setVerticalGroup(
            Search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SBSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        Home_panel1.setBackground(new java.awt.Color(0, 0, 102));
        Home_panel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        Edit_panel.setBackground(new java.awt.Color(255, 255, 255));
        Edit_panel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Edit_panel.setForeground(new java.awt.Color(255, 255, 255));
        Edit_panel.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\edit2.png")); // NOI18N
        Edit_panel.setText("EDIT COURSE");
        Edit_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Edit_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Edit_panelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Home_panel1Layout = new javax.swing.GroupLayout(Home_panel1);
        Home_panel1.setLayout(Home_panel1Layout);
        Home_panel1Layout.setHorizontalGroup(
            Home_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Edit_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        Home_panel1Layout.setVerticalGroup(
            Home_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Edit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Home_panel2.setBackground(new java.awt.Color(0, 0, 102));
        Home_panel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        Course_panel.setBackground(new java.awt.Color(255, 255, 255));
        Course_panel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Course_panel.setForeground(new java.awt.Color(255, 255, 255));
        Course_panel.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\list.png")); // NOI18N
        Course_panel.setText("COURSE LIST");
        Course_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Course_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Course_panelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Home_panel2Layout = new javax.swing.GroupLayout(Home_panel2);
        Home_panel2.setLayout(Home_panel2Layout);
        Home_panel2Layout.setHorizontalGroup(
            Home_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Course_panel)
                .addGap(33, 33, 33))
        );
        Home_panel2Layout.setVerticalGroup(
            Home_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Course_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        View_panel.setBackground(new java.awt.Color(0, 0, 102));
        View_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        SBView.setBackground(new java.awt.Color(255, 255, 255));
        SBView.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SBView.setForeground(new java.awt.Color(255, 255, 255));
        SBView.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\view all record.png")); // NOI18N
        SBView.setText("VIEW ALL RECORD");
        SBView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SBViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SBViewMouseExited(evt);
            }
        });

        javax.swing.GroupLayout View_panelLayout = new javax.swing.GroupLayout(View_panel);
        View_panel.setLayout(View_panelLayout);
        View_panelLayout.setHorizontalGroup(
            View_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SBView)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        View_panelLayout.setVerticalGroup(
            View_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SBView, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        Logout_panel.setBackground(new java.awt.Color(0, 0, 102));
        Logout_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        SBLogout.setBackground(new java.awt.Color(255, 255, 255));
        SBLogout.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        SBLogout.setForeground(new java.awt.Color(255, 255, 255));
        SBLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\logout.png")); // NOI18N
        SBLogout.setText("LOGOUT");
        SBLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SBLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SBLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Logout_panelLayout = new javax.swing.GroupLayout(Logout_panel);
        Logout_panel.setLayout(Logout_panelLayout);
        Logout_panelLayout.setHorizontalGroup(
            Logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Logout_panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(SBLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Logout_panelLayout.setVerticalGroup(
            Logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Logout_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SBLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        Back_panel.setBackground(new java.awt.Color(0, 0, 102));
        Back_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        SBBack.setBackground(new java.awt.Color(255, 255, 255));
        SBBack.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        SBBack.setForeground(new java.awt.Color(255, 255, 255));
        SBBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\pande\\OneDrive\\Desktop\\Christ University\\2nd Semester\\Java\\Mini_project\\my icons\\back1.png")); // NOI18N
        SBBack.setText("BACK");
        SBBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SBBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SBBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Back_panelLayout = new javax.swing.GroupLayout(Back_panel);
        Back_panel.setLayout(Back_panelLayout);
        Back_panelLayout.setHorizontalGroup(
            Back_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Back_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SBBack)
                .addGap(100, 100, 100))
        );
        Back_panelLayout.setVerticalGroup(
            Back_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Back_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SBBack, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Home_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Home_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(View_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Home_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Home_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Home_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(View_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Back_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Logout_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Id.setText("CU-ID :");

        IdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextActionPerformed(evt);
            }
        });

        PayMode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PayMode.setText("PAYMENT MODE:");

        PayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayTextActionPerformed(evt);
            }
        });

        ChequeNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChequeNum.setText("CHECK NUMBER:");

        ChequeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChequeTextActionPerformed(evt);
            }
        });

        BankNm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BankNm.setText("BANK NAME:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        BankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankTextActionPerformed(evt);
            }
        });

        Receiver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Receiver.setText("RECIEVED FROM:");

        ReceiverText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiverTextActionPerformed(evt);
            }
        });

        Course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Course.setText("COURSE:");

        CourseText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSC-DS", "MSC-DS", "BBA", "MBA", "BCOM", "MCOM", "LLB", "LLM" }));
        CourseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseTextActionPerformed(evt);
            }
        });

        AmountRup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AmountRup.setText("AMOUNT(in Rupees):");

        AmountRupText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountRupTextActionPerformed(evt);
            }
        });

        AmountWords.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AmountWords.setText("AMOUNT(in Words):");

        AmountWordsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountWordsTextActionPerformed(evt);
            }
        });

        Remarks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Remarks.setText("REMARKS(if any):");

        RemarksText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemarksTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Receiver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChequeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PayMode, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PayText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AmountWords, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemarksText, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AmountWordsText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(134, 134, 134)
                                    .addComponent(AmountRup, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(181, 181, 181)
                                    .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CourseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AmountRupText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(BankNm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(77, 77, 77)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ReceiverText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BankText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChequeText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48))))
                .addContainerGap(863, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayMode)
                    .addComponent(PayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChequeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChequeNum))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankNm)
                    .addComponent(BankText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Receiver)
                    .addComponent(ReceiverText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course)
                    .addComponent(CourseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountRup)
                    .addComponent(AmountRupText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountWords)
                    .addComponent(AmountWordsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Remarks)
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(RemarksText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 834, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(4054, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SBHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBHomeMouseEntered
        Color clr=new Color(0,153,153);
        Home_panel.setBackground(clr);
        
    }//GEN-LAST:event_SBHomeMouseEntered

    private void SBHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBHomeMouseExited
        Color clr=new Color(0,103,103);
        Home_panel.setBackground(clr);
    }//GEN-LAST:event_SBHomeMouseExited

    private void SBSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBSearchMouseEntered
        Color clr=new Color(0,153,153);
        Search_panel.setBackground(clr);
    }//GEN-LAST:event_SBSearchMouseEntered

    private void SBSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBSearchMouseExited
        Color clr=new Color(0,103,103);
        Search_panel.setBackground(clr);
    }//GEN-LAST:event_SBSearchMouseExited

    private void Edit_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_panelMouseEntered
        Color clr=new Color(0,153,153);
        Edit_panel.setBackground(clr);
    }//GEN-LAST:event_Edit_panelMouseEntered

    private void Edit_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_panelMouseExited
        Color clr=new Color(0,103,103);
        Edit_panel.setBackground(clr);
    }//GEN-LAST:event_Edit_panelMouseExited

    private void Course_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Course_panelMouseEntered
        Color clr=new Color(0,153,153);
        Course_panel.setBackground(clr);
    }//GEN-LAST:event_Course_panelMouseEntered

    private void Course_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Course_panelMouseExited
        Color clr=new Color(0,103,103);
        Course_panel.setBackground(clr);
    }//GEN-LAST:event_Course_panelMouseExited

    private void SBViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBViewMouseEntered
        Color clr=new Color(0,153,153);
        View_panel.setBackground(clr);
    }//GEN-LAST:event_SBViewMouseEntered

    private void SBViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBViewMouseExited
        Color clr=new Color(0,103,103);
        View_panel.setBackground(clr);
    }//GEN-LAST:event_SBViewMouseExited

    private void SBLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBLogoutMouseEntered
        Color clr=new Color(0,153,153);
        Logout_panel.setBackground(clr);
    }//GEN-LAST:event_SBLogoutMouseEntered

    private void SBLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBLogoutMouseExited
        Color clr=new Color(0,103,103);
        Logout_panel.setBackground(clr);
    }//GEN-LAST:event_SBLogoutMouseExited

    private void SBBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBBackMouseEntered
        Color clr=new Color(0,153,153);
        Back_panel.setBackground(clr);
    }//GEN-LAST:event_SBBackMouseEntered

    private void SBBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBBackMouseExited
        Color clr=new Color(0,103,103);
        Back_panel.setBackground(clr);
    }//GEN-LAST:event_SBBackMouseExited

    private void IdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextActionPerformed

    private void PayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayTextActionPerformed

    private void ChequeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChequeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChequeTextActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void BankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankTextActionPerformed

    private void ReceiverTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiverTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceiverTextActionPerformed

    private void CourseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseTextActionPerformed

    private void AmountRupTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountRupTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountRupTextActionPerformed

    private void AmountWordsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountWordsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountWordsTextActionPerformed

    private void RemarksTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemarksTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemarksTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountRup;
    private javax.swing.JTextField AmountRupText;
    private javax.swing.JLabel AmountWords;
    private javax.swing.JTextField AmountWordsText;
    private javax.swing.JPanel Back_panel;
    private javax.swing.JLabel BankNm;
    private javax.swing.JTextField BankText;
    private javax.swing.JLabel ChequeNum;
    private javax.swing.JTextField ChequeText;
    private javax.swing.JLabel Course;
    private javax.swing.JComboBox<String> CourseText;
    private javax.swing.JLabel Course_panel;
    private javax.swing.JLabel Edit_panel;
    private javax.swing.JPanel Home_panel;
    private javax.swing.JPanel Home_panel1;
    private javax.swing.JPanel Home_panel2;
    private javax.swing.JLabel Id;
    private javax.swing.JTextField IdText;
    private javax.swing.JPanel Logout_panel;
    private javax.swing.JLabel PayMode;
    private javax.swing.JTextField PayText;
    private javax.swing.JLabel Receiver;
    private javax.swing.JTextField ReceiverText;
    private javax.swing.JLabel Remarks;
    private javax.swing.JTextField RemarksText;
    private javax.swing.JLabel SBBack;
    private javax.swing.JLabel SBHome;
    private javax.swing.JLabel SBLogout;
    private javax.swing.JLabel SBSearch;
    private javax.swing.JLabel SBView;
    private javax.swing.JPanel Search_panel;
    private javax.swing.JPanel View_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
